# Site
repository: sproogen/resume-theme 

# Personal info
name: Mattia Molinaro
title: Data Scientist | Statistician | Mathematician
email: mattia.molinaro ■ gmail.com

# Social links
github_username:  molinaromattia
linkedin_username: mattia-molinaro-a3816870

# About Section
about_title: Who is Mattia?
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello and welcome to my online resume! I am Mattia, a data analytics expert with broad practical industrial experience ranging from a healthcare start-up to major investment banks. As a trained mathematician, I strive to excel in this domain by constantly expanding my knowledge of statistics and machine learning for big data and “small data” - the latter being not so mainstream these days, yet of extreme importance in many contexts. 
  
  The "customer" is at the core of each and every data analytics project I work on, and the impact on their business is the main driving factor in my daily tasks. After slicing, dicing and modeling that data with the latest technologies, I eagerly present my results and insights to peers as well as to senior management. I am a native Italian speaker and fluent in English and German. Currently I am trying to broaden my linguistical horizons by learning Mandarin :) 

  My specialties are: <mark>statistics</mark>, <mark>machine learning</mark>, <mark>R</mark>, <mark>Python</mark>, <mark>SQL</mark> and <mark>Spark</mark>



# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Professional experience

# Education Section
# educaton_title: Education

# More Section
more_title: Computer skills and data libraries
more_content: | # this will include new lines to allow paragraphs
  * **Languages:** `R` (advanced) – `SQL` (advanced, projects in `PostgreSQL`, `SparkSQL` and `MySQL`) – `Python` (data libraries, intermediate) – `Matlab` (intermediate) 
  * **R libraries:** among many,`ggplot2`, `dplyr` (data preprocessing and visualization), `caret` (machine learning), `h2o` (feed forward networks models and machine learning workflow automation), `knitr` (dynamic report generation)
  * **Python libraries:**: `numpy`, `pandas` (numerical simulation and data preprocessing), `seaborn`
  (data visualization), `statsmodels`, `scikit-learn` (statistics and machine learning), `PySpark` (Python API for Spark)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
