# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Mattia Molinaro
title: Data Scientist | Statistician
email: mattia.molinaro ■ gmail.com

# Social links
# twitter_username: facespics
github_username:  molinaromattia
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: mattia-molinaro-a3816870
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: Who is Mattia?
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello and welcome to my online resume! I am Mattia, a data analytics expert with broad practical industrial experience ranging from a healthcare start-up to major investment banks. As a trained mathematician, I wholeheartedly believe that to excel in this domain one needs to have sound theoretical and practical knowledge of statistics and machine learning for big data and “small data”. 
  
  Besides this, the "customer" is at the core of each and every data analytics project, and the impact on their business is the main driving factor in my daily tasks. After slicing and dicing the data with the latest technologies, I wear my suit and eagerly present my results and findings to my colleagues up to senior management. I am a native Italian speaker and fluent in English and German. Currently I am trying to broaden my linguistical horizons by learning Mandarin :) 

  My specialties are: <mark>statistics</mark>, <mark>machine learning</mark>, <mark>R</mark>, <mark>Python</mark>, <mark>SQL</mark> and <mark>Spark</mark>



# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Professional experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs
#  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#   - Rock climbing
#   - Gaming
#   - Knitting
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
